name: cf_compact
channels:
  - pytorch
  - nvidia
  - pytorch3d
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=12.1
  - faiss-cpu=1.7.4
  - mkl=2021
  - blas=1.0=mkl
  - cudatoolkit-dev
  - pip
  - pip:
    - tyro
    - open_clip_torch
    - wandb
    - h5py
    - openai
    - hydra-core
    - distinctipy
    - ultralytics
    - dill
    - supervision
    - open3d
    - imageio
    - natsort
    - kornia
    - rerun-sdk
    - pyliblzfse
    - pypng
    - git+https://github.com/ultralytics/CLIP.git
    - https://anaconda.org/pytorch3d/pytorch3d/0.7.4/download/linux-64/pytorch3d-0.7.4-py310_cu118_pyt201.tar.bz2